export default function Footer() {
  return (
    <footer className="w-full h-10 border-t border-[#D4D0C8] bg-[#FAF8F4] flex items-center px-6">
      <div className="w-full max-w-[1440px] mx-auto">
        <p className="font-mono text-[11px] text-[#6B6B6B] leading-none">
          Prices: LME official (EOD) + COMEX via Yahoo Finance.&ensp;Sentiment &amp; brief generated by Claude.
        </p>
      </div>
    </footer>
  )
}
